# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
comments:            true

# Setup
title:               App Lens
tagline:             'A closer look at interesting mobile apps'
description:         'An opinion blog threading together mobile app UX, technology, culture and business'
url:                 http://kowlgi.github.io
baseurl:             ""
paginate:            1

# About/contact
author:
  name:              Sunil Kowlgi
  url:               https://twitter.com/kowlgi

# Custom vars
version:             1.0.0
