# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Sunil Kowlgi
tagline:             'Analysis and opinions on mobile apps'
description:         'A blog with analysis and opinions on mobile apps'
url:                 http://kowlgi.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sunil Kowlgi
  url:               https://twitter.com/kowlgi

# Custom vars
version:             1.0.0
